throw new Error('Retired: this per-item Math AA writer may not modify the bank. Use install_ib_math_aa_structured_batch.cjs with a fully reviewed batch payload.')
const fs=require('fs'),path=require('path')
const {reviewBasisHash}=require('./lib/ib_math_aa_knowledge_classifier.cjs')
const root=path.resolve(__dirname,'..'),bp=path.join(root,'public','data','ib','math-aa-sl','paper_bank.json'),bank=JSON.parse(fs.readFileSync(bp,'utf8'))
const q=bank.find(x=>x.question_id==='P2-000054'); if(!q)throw Error('P2-000054 not found')
const part=(label,marks,text)=>({label,marks,text,scheme:rows.find(r=>r.part===label).text})
const rows=[
{part:'a',marks:2,text:'recognising to find \\(P(T>40)\\) (M1)\\n\\[P(T>40)=0.574136\\ldots\\]\\n\\[P(T>40)=0.574\\] (A1)',mark_points:[
{id:'MP1',part_label:'a',code:'M1',marks:1,description:'recognising to find \\(P(T>40)\\); \\(P(T>40)=0.574136\\ldots\\)',knowledge_point_codes:['AA-4.9']},
{id:'MP2',part_label:'a',code:'A1',marks:1,description:'\\(P(T>40)=0.574\\)',knowledge_point_codes:['AA-4.9']} ]},
{part:'b',marks:3,text:'attempt to multiply four independent probabilities using their \\(P(T>40)\\) and \\(P(T<40)\\) (M1)\\n\\[(1-p)^3\\cdot p\\quad\\text{OR}\\quad(1-0.574136\\ldots)^3\\cdot0.574136\\ldots\\quad\\text{OR}\\quad(0.425863\\ldots)^3\\cdot0.574136\\ldots\\] (A1)\\n\\[0.0443430\\ldots\\]\\n\\[0.0443\\ ,\\ 0.0444\\text{ from 3 sf values}\\] (A1)',mark_points:[
{id:'MP3',part_label:'b',code:'M1',marks:1,description:'attempt to multiply four independent probabilities using their \\(P(T>40)\\) and \\(P(T<40)\\)',knowledge_point_codes:['AA-4.8']},
{id:'MP4',part_label:'b',code:'A1',marks:1,description:'\\((1-p)^3\\cdot p\\) OR \\((1-0.574136\\ldots)^3\\cdot0.574136\\ldots\\) OR \\((0.425863\\ldots)^3\\cdot0.574136\\ldots\\)',knowledge_point_codes:['AA-4.8']},
{id:'MP5',part_label:'b',code:'A1',marks:1,description:'\\(0.0443\\), \\(0.0444\\) from 3 sf values',knowledge_point_codes:['AA-4.8']}]},
{part:'c.i',marks:4,text:'recognising conditional probability (M1)\\n\\[P(T<55\\mid T>40)\\]\\nNote: Award (M1) for an expression or description in context. Accept \\(P(T>40\\mid T<55)\\) but do not accept just \\(P(A\\mid B)\\).\\n\\[\\frac{P(40<T<55)}{P(T>40)}\\] (A1)\\n\\[\\frac{0.461944\\ldots}{0.574136\\ldots}\\] (A1)\\n\\[P(T<55\\mid T>40)=0.804590\\ldots=0.805\\] (A1)',mark_points:[
{id:'MP6',part_label:'c.i',code:'M1',marks:1,description:'recognising conditional probability; \\(P(T<55\\mid T>40)\\). Award (M1) for an expression or description in context. Accept \\(P(T>40\\mid T<55)\\) but do not accept just \\(P(A\\mid B)\\).',knowledge_point_codes:['AA-4.11']},
{id:'MP7',part_label:'c.i',code:'A1',marks:1,description:'\\(\\frac{P(40<T<55)}{P(T>40)}\\)',knowledge_point_codes:['AA-4.11']},
{id:'MP8',part_label:'c.i',code:'A1',marks:1,description:'\\(\\frac{0.461944\\ldots}{0.574136\\ldots}\\)',knowledge_point_codes:['AA-4.9']},
{id:'MP9',part_label:'c.i',code:'A1',marks:1,description:'\\(P(T<55\\mid T>40)=0.804590\\ldots=0.805\\)',knowledge_point_codes:['AA-4.11']}]},
{part:'c.ii',marks:3,text:'recognising binomial probability (M1)\\n\\[X\\sim B(n,p)\\]\\n\\[n=10\\text{ and }p=0.804589\\ldots\\] (A1)\\n\\[0.0242111\\ldots,\\ 0.0240188\\ldots\\text{ using }p=0.805\\]\\n\\[P(X=5)=0.0242\\] (A1)',mark_points:[
{id:'MP10',part_label:'c.ii',code:'M1',marks:1,description:'recognising binomial probability; \\(X\\sim B(n,p)\\)',knowledge_point_codes:['AA-4.8']},
{id:'MP11',part_label:'c.ii',code:'A1',marks:1,description:'\\(n=10\\) and \\(p=0.804589\\ldots\\)',knowledge_point_codes:['AA-4.8']},
{id:'MP12',part_label:'c.ii',code:'A1',marks:1,description:'\\(0.0242111\\ldots\\), \\(0.0240188\\ldots\\) using \\(p=0.805\\); \\(P(X=5)=0.0242\\)',knowledge_point_codes:['AA-4.8']}]},
{part:'d',marks:4,text:'Let \\(P(T<a)=x\\).\\nrecognition that probabilities sum to 1 (seen anywhere) (M1)\\nEITHER\\nexpressing the three regions in one variable (M1)\\n\\[x+0.904+2x\\quad\\text{OR}\\quad P(T<a)+0.904+2P(T<a)\\quad\\text{OR}\\quad\\frac12P(T>b)+0.904+P(T>b)\\]\\nOR \\(x\\) and \\(2x\\) correctly indicated on labelled bell diagram\\n\\[P(T<a)+0.904+2P(T<a)=1\\quad\\text{OR}\\quad\\frac12P(T>b)+0.904+P(T>b)=1\\text{ (or equivalent)}\\] (A1)\\nOR\\nexpressing either \\(P(T<a)\\) or \\(P(T>b)\\) only in terms of \\(P(a\\le T\\le b)\\) (M1)\\n\\[P(T<a)=\\frac13(1-P(a\\le T\\le b))\\quad\\text{OR}\\quad P(T>b)=\\frac23(1-P(a\\le T\\le b))\\]\\n\\[x=\\frac13(1-0.904)(=0.032)\\quad\\text{OR}\\quad P(T>b)=\\frac23(1-0.904)(=0.064)\\] (A1)\\nTHEN\\n\\[P(T<a)=0.032\\]\\n\\[a=22.18167\\ldots\\]\\n\\[a=22.2\\text{ accept }22.1\\] (A1)',mark_points:[
{id:'MP13',part_label:'d',code:'M1',marks:1,description:'recognition that probabilities sum to 1 (seen anywhere)',knowledge_point_codes:['AA-4.9']},
{id:'MP14',part_label:'d',code:'M1',marks:1,description:'EITHER expressing the three regions in one variable: \\(x+0.904+2x\\) OR \\(P(T<a)+0.904+2P(T<a)\\) OR \\(\\frac12P(T>b)+0.904+P(T>b)\\), OR \\(x\\) and \\(2x\\) correctly indicated on labelled bell diagram; OR expressing either \\(P(T<a)\\) or \\(P(T>b)\\) only in terms of \\(P(a\\le T\\le b)\\).',knowledge_point_codes:['AA-4.9']},
{id:'MP15',part_label:'d',code:'A1',marks:1,description:'\\(P(T<a)+0.904+2P(T<a)=1\\) OR \\(\\frac12P(T>b)+0.904+P(T>b)=1\\) (or equivalent); OR \\(x=\\frac13(1-0.904)(=0.032)\\) OR \\(P(T>b)=\\frac23(1-0.904)(=0.064)\\).',knowledge_point_codes:['AA-4.12']},
{id:'MP16',part_label:'d',code:'A1',marks:1,description:'\\(P(T<a)=0.032\\); \\(a=22.18167\\ldots\\); \\(a=22.2\\), accept \\(22.1\\)',knowledge_point_codes:['AA-4.12']}]}];
const parts=[part('a',2,'Find the probability that an employee selected at random works more than 40 hours per week.'),part('b',3,'A group of four employees is selected at random. Each employee is asked in turn whether they work more than 40 hours per week. Find the probability that the fourth employee is the only one in the group who works more than 40 hours per week.'),part('c.i',4,'An employee is selected at random from this large group. Find the probability that this employee works less than 55 hours per week.'),part('c.ii',3,'Ten employees are selected at random from this large group. Find the probability that exactly five of them work less than 55 hours per week.'),part('d',4,'Find the maximum time, in hours per week, that an employee can work and still be considered part-time.')];
q.text='The time worked, \\(T\\), in hours per week by employees of a large company is normally distributed with a mean of 42 and standard deviation 10.7. '+parts.map(p=>`(${p.label}) ${p.text}`).join(' ')+ ' It is known that \\(P(a\\le T\\le b)=0.904\\) and that \\(P(T>b)=2P(T<a)\\), where \\(a\\) and \\(b\\) are numbers of hours worked per week. An employee who works fewer than \\(a\\) hours per week is considered to be a part-time employee.';
q.content={stem_blocks:[{type:'paragraph',text:'The time worked, \\(T\\), in hours per week by employees of a large company is normally distributed with a mean of 42 and standard deviation 10.7.'},{type:'paragraph',text:'A large group of employees work more than 40 hours per week.'},{type:'paragraph',text:'It is known that \\(P(a\\le T\\le b)=0.904\\) and that \\(P(T>b)=2P(T<a)\\), where \\(a\\) and \\(b\\) are numbers of hours worked per week. An employee who works fewer than \\(a\\) hours per week is considered to be a part-time employee.'}],parts:parts.map(p=>({label:p.label,marks:p.marks,blocks:[{type:'paragraph',text:p.text}]}))};
q.parts=parts;q.part_marks=parts.map(p=>({label:p.label,marks:p.marks}));q.answers=[{part:'a',text:'\\(0.574\\).'},{part:'b',text:'\\(0.0443\\), or \\(0.0444\\) from 3 sf values.'},{part:'c.i',text:'\\(0.805\\).'},{part:'c.ii',text:'\\(0.0242\\).'},{part:'d',text:'\\(22.2\\) hours, accept \\(22.1\\).'}];q.solution={outline:'Official calculation path is recorded in the complete official markscheme rows.'};q.markscheme={rows,mark_points:rows.flatMap(r=>r.mark_points)};q.transcription_status='structured_reviewed';q.display_mode='structured';q.publication_review={...q.publication_review,transcription_basis:'complete structured transcription checked against rendered question and all three official markscheme pages'};
const ph=q.source.paper_sha256,mh=q.source.markscheme_sha256,pa=q.source_images[0].sha256,ma=q.markscheme_images.map(x=>x.sha256);q.structured_field_audit=[...q.content.stem_blocks.map((_,i)=>({field_path:`content.stem_blocks[${i}]`,source_role:'question',source_file_sha256:ph,source_page:13,asset_sha256:pa})),...parts.map(p=>({field_path:`content.parts[${p.label}]`,source_role:'question',source_file_sha256:ph,source_page:13,asset_sha256:pa})),...q.answers.map(a=>({field_path:`answers[${a.part}]`,source_role:'markscheme',source_file_sha256:mh,source_pages:a.part==='a'||a.part==='b'?[21]:a.part.startsWith('c')?[22]:[23]})),...rows.map(r=>({field_path:`markscheme.rows[${r.part}]`,source_role:'markscheme',source_file_sha256:mh,source_pages:r.part==='a'||r.part==='b'?[21]:r.part.startsWith('c')?[22]:[23]}))];
q.knowledge_point_classification={...q.knowledge_point_classification,review_basis_sha256:reviewBasisHash(q),evidence:[`question source ${ph}`,`markscheme source ${mh}`,'verified 16 scoring marks across 5 part(s)']};
const lp=path.join(root,'public','data','ib','math-aa','item_classification_ledger.json'),ledger=JSON.parse(fs.readFileSync(lp,'utf8')),l=ledger.items.find(x=>x.subject_id==='ib-math-aa-sl'&&x.question_id===q.question_id);if(!l)throw Error('ledger missing');l.review_basis_sha256=reviewBasisHash(q);l.mark_point_count=16;fs.writeFileSync(bp,JSON.stringify(bank,null,2)+'\\n','utf8');fs.writeFileSync(lp,JSON.stringify(ledger,null,2)+'\\n','utf8');console.log('Installed P2-000054')
